# this is an extension file for the base docker-compose.yml file
# usage: docker-compose -f docker-compose.yml -f docker-compose.production.yml ...
version: '2'
services:
  app:
    image: ydashboard_app:production
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE
    volumes:
      - ydashboard-assets:/ydashboard/www
      - ydashboard-assets-cache:/ydashboard/app/tmp/cache/assets
    command: bash -c "bundle exec bin/rails assets:precompile && rm -rf /ydashboard/www/* && cp -r /ydashboard/app/public/* /ydashboard/www/ && bundle exec bin/rails s -b '0.0.0.0'"
  worker:
    image: ydashboard_app:production
    environment:
      - RAILS_ENV=production
  web:
    image: ydashboard_nginx
    build:
      context: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ydashboard-assets:/ydashboard/www:ro
    depends_on:
      - app

volumes:
  ydashboard-assets:
  ydashboard-assets-cache:
