version: '2'
services:
  davical:
    image: calendar-davical
    build:
      context: davical
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: on-failure
  agendav:
    image: calendar-agendav
    build:
      context: agendav-debian
    environment:
      - AGENDAV_SERVER_NAME=127.0.0.1
      - AGENDAV_TITLE=Calendar
      - AGENDAV_FOOTER=Agendav
      - AGENDAV_ENC_KEY=my_encrypt10n_k3y
      - AGENDAV_CALDAV_SERVER=http://davical
      - AGENDAV_TIMEZONE=Europe/Prague
      - AGENDAV_LANG=en
      - AGENDAV_LOG_DIR=/tmp/
    ports:
      - "80:80"
    restart: on-failure
  postgres:
    image: calendar-postgres
    build:
      context: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - calendar-postgres:/var/lib/postgresql
    restart: on-failure

volumes:
  calendar-postgres:
