version: '2'
services:
  davical:
    image: calendar-davical
    build:
      context: davical
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: on-failure
  # agendav:
  #   image: calendar-agendav
  #   build:
  #     context: agendav
  #   # command: bundle exec rake jobs:work
  #   environment:
  #     # - RAILS_LOG_TO_STDOUT=1
  #     # - RAILS_ENV
  #   depends_on:
  #     - postgres
  #   restart: on-failure
  postgres:
    image: calendar-postgres
    build:
      context: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - calendar-postgres:/var/lib/postgresql
    restart: on-failure

volumes:
  calendar-postgres:
